nonrigid_registration:
  autotune: 'False'
  gamma: 10
  beta: 2
  decimation: 'False'
  distance_threshold: 1e-8
  lambda: 10
  downsampling: 'Y, 26443, 0.05'
  max_iterations: 1000
  seed: 26
rigid_registration:
  global_distance_threshold_factor: 0.23
  global_edge_length_threshold_factor: 0.95
  global_max_correspondence: 0.999
  global_max_iterations: 100000
  max_nn: 100
  refine_distance_threshold_factor: 0.1
  voxel_size: 0.025
